### ISSUE TITLE
Space alignment

### ISSUE THREAD

**Issue by RajeshkumarA-Contus** [Codewaves/Sticky-Header-Grid#10]
Hi,

This library was working fine. But i cannot use equal space for grid items.  Even if i add any other item decorator, it was affecting sticky header too. Is there is any solution?

**Comment by Codewaves** [comment]
Can you provide example code or screenshot of the problem?

**Comment by D330** [comment]
+1 if i set margin on item view for example 3 items in row, on every 6dp. On the left of end item of row 6 + 6 + 6 = 18dp.. When i clear margins all items placed together... any ideas?

**Comment by Codewaves** [comment]
You need to create separate item layout for leftmost or rightmost column with different margin.
