### ISSUE TITLE
IndexOutOfBoundError after changing SPAN_SIZE value less than 3

### ISSUE THREAD

**Issue by latymumb** [Codewaves/Sticky-Header-Grid#14]
> java.lang.ArrayIndexOutOfBoundsException: length=1; index=-1
>                                                                                            at com.codewaves.stickyheadergrid.StickyHeaderGridLayoutManager.fillBottomRow(StickyHeaderGridLayoutManager.java:546)
>                                                                                            at com.codewaves.stickyheadergrid.StickyHeaderGridLayoutManager.onLayoutChildren(StickyHeaderGridLayoutManager.java:406)

please take a look on `new StickyHeaderGridLayoutManager(SPAN_SIZE);`

**Comment by Codewaves** [comment]
If you change span size, you must correctly implement SpanSizeLookup#getSpanSize method. Make sure it returns value in range 1..SPAN_SIZE
