### ISSUE TITLE
How to disable headers?

### ISSUE THREAD

**Issue by Konrad-Morawski** [Codewaves/Sticky-Header-Grid#15]
I'm testing the library. I appreciate your work. 

My question is, what's the best way for actually _disabling_ the headers functionality? 

The point is that I don't always need them on the `RecyclerView` I'm using, so I'd like to be able to switch it off conditionally. 

Is the recommended way to simply return empty / invisible Views from `onCreateHeaderViewHolder`? This seems to do the trick, but I wonder if there was perhaps some more elegant way of accomplishing this.

**Comment by Codewaves** [comment]
I don't think that there is another way. Library doesn't support headers hide.

**Comment by D330** [comment]
Just give header view Visibility.GONE
