### ISSUE TITLE
How to change item view type?

### ISSUE THREAD

**Issue by Hapsidra** [Codewaves/Sticky-Header-Grid#8]
Hello, great work! How i can change item view type? I want use in 3 first items different view. How i can do it?

**Comment by Codewaves** [comment]
Override getSectionItemViewType and return item type, onCreateItemViewHolder's itemType will be your custom item type.

**Comment by Hapsidra** [comment]
I override this method inside my item holder, but onCreateItemViewHolder's itemType is 0 for every time (

**Comment by Hapsidra** [comment]
oh, sorry, i had override getSectionItemViewType(int section, int offset) method. Thank you for help 👍
